### ISSUE TITLE
请问支持中文枚举么?如何编写规则呢?

### ISSUE THREAD

**Issue by summarychm** [WhatAKitty/react-native-fetch-mock#1]
我想使用Mock的中文枚举功能,但是没有生效.
我编写的测试规则为
'array|2': [
    "AMD",
    "CMD",
    "UMD"
  ]

**Comment by WhatAKitty** [comment]
```
'array|2': [
"你好1",
"你好2",
"你好3"
]
```
我结合的是Mock.js插件，其他具体的规则，你可以查看这个链接：[Mock.js](http://mockjs.com/)

**Comment by summarychm** [comment]
好的，我再试试，多谢！

发自我的 Windows Phone
________________________________
发件人: WhatAKitty<mailto:notifications@github.com>
发送时间: ‎2017/‎4/‎23 18:48
收件人: WhatAKitty/react-native-fetch-mock<mailto:react-native-fetch-mock@noreply.github.com>
抄送: summarychm<mailto:summarychm@hotmail.com>; Author<mailto:author@noreply.github.com>
主题: Re: [WhatAKitty/react-native-fetch-mock] 请问支持中文枚举么?如何编写规则呢? (#1)


'array|2': [ "你好1", "你好2", "你好3" ]

我结合的是Mock.js插件，其他具体的规则，你可以查看这个链接：Mock.js<http://mockjs.com/>
