### ISSUE TITLE
ReferenceError: url is not defined

### ISSUE THREAD

**Issue by gmisa** [WhatAKitty/react-native-fetch-mock#3]
What am i doing wrong?

Thanks

`//test.e2e.js`

`import FetchMock from 'react-native-fetch-mock';`

`if (__DEV__) {`
&nbsp;&nbsp;&nbsp;`global.fetch = new FetchMock(require('../../__mocks__')).fetch;`
`}`

`function mockGetProfileAPI(token) {`
&nbsp;&nbsp;&nbsp;`return fetch('https://api.xxx.com/profile', {`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`method: 'GET',`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`headers:{`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`Authorization: v => v === Bearer ${token},`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`'content-type': () => true,`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`'accept-encoding': () => true,`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;` 'user-agent': () => true,`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`connection: () => true,`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`accept: () => true,`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`'content-length': () => true,`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`},`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`body: {`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`data: {`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`attributes: {`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`...attributes,`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`}`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`}`
&nbsp;&nbsp;&nbsp;`},`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`url: 'https://api.xxx.com/profile'`
&nbsp;&nbsp;&nbsp;`});`
`}`

`mockGetProfileAPI('mytoken');`

`//__mocks__/index.js`

`export default {`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`'https://api.xxx.com/profile': ({ method, headers, body, url }) => {`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`return {`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`status: 201,`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`data: {"attributes": {"name": "Guillermo"}}`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`};`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`}`
`}`

Below is the stack trace:
ReferenceError: url is not defined

      at FetchMock.matchReqUrl (node_modules/react-native-fetch-mock/src/index.js:81:1678)

      at FetchMock.fetch (node_modules/react-native-fetch-mock/src/index.js:81:1841)

      at mockGetProfileAPI

**Comment by WhatAKitty** [comment]
It worked for me:
index.js
```
import { AppRegistry } from 'react-native';
import App from './App';
import FetchMock from 'react-native-fetch-mock';

if (__DEV__) {
  global.fetch = new FetchMock(require('./__mocks__')).fetch;
}

function mockGetProfileAPI(token) {
  return fetch('https://api.xxx.com/profile', {
    method: 'GET',
    headers: {
      Authorization: v => v === 'Bearer ${token}',
      'content-type': () => true,
      'accept-encoding': () => true,
      'user-agent': () => true,
      connection: () => true,
      accept: () => true,
      'content-length': () => true,
    },
    body: {
      data: {
        attributes: {
          a: 1,
        }
      }
    },
    url: 'https://api.xxx.com/profile'
  });
}

const getResult = async () => {
  const { data, err } = await mockGetProfileAPI('mytoken').then(res => res.json()).then(data => ({data})).catch(err => ({err}));
  alert(JSON.stringify(data));
}

getResult();

AppRegistry.registerComponent('rnFetchMockIssue', () => App);

```

__mocks__/index.js
```
export default {
  'https://api.xxx.com/profile': ({ method, headers, body, url }) => {
    return {
      status: 201,
      data: { "attributes": { "name": "Guillermo" } }
    };
  }
}

```
