### ISSUE TITLE
Can't find variable: Symbol

### ISSUE THREAD

**Issue by Hunsu** [WhatAKitty/react-native-fetch-mock#5]
When using the module I get that error. It was fixed when I added babel-polyfill but then I got warnnings:

    Warning: Failed prop type: Invalid prop `children` of type `object` supplied to `Provider`, expected a single ReactElement.

**Comment by WhatAKitty** [comment]
What's your react version?
And is there have an repo to reproduce this issue?

**Comment by Hunsu** [comment]
I'm using React Native 0.52 with Expo. I will make repo with the reproduction issues later this day.

**Comment by Hunsu** [comment]
Here is reproduction repo https://github.com/Hunsu/react-native-fetch-mock-issue-5

After `yarn install` you will get the error about the Symbol.

**Comment by WhatAKitty** [comment]
@Hunsu I have using the react versioned 0.52 and it worked well, and the Expo that you said I have never used it before. I will try to find what's the problem that caused this issue.

**Comment by Hunsu** [comment]
Expo uses a forked version of react native. I will use the non forked version of react native to see if I reproduce the issue.

**Comment by WhatAKitty** [comment]
@Hunsu ok, I will wait. I tried start your repo with Expo, but failed to start.

**Comment by Hunsu** [comment]
I have the same issue when React Native 0.52. What errors did you get when starting the repro app?

**Comment by Hunsu** [comment]
Apparently the Symbol feature is not supported by Expo on Android.
