### ISSUE TITLE
[Enhancement] Exclude all non-matched option

### ISSUE THREAD

**Issue by Raido0812** [WhatAKitty/react-native-fetch-mock#6]
Functionality to Exclude is awesome, but depending on project they might only want to mock a few calls and exclude all others. Perhaps an additional option to allow all non-matched urls to fallback to raw. Similar to [fetch-mock](http://www.wheresrhys.co.uk/fetch-mock/#usageconfiguration)'s fallbackToNetwork option

**Comment by WhatAKitty** [comment]
sounds not bad, are you want to pull request for this?

**Comment by WhatAKitty** [comment]
Down with new version 0.9.0
